export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpg",
    username: "Василиса Дроздова",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpg",
    username: "Ксения Максимова",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpg",
    username: "Валерия Воробьева",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpg",
    username: "Алексей Мухин",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpg",
    username: "Даниил Балашов",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpg",
    username: "Вера Журавлева",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpg",
    username: "Виктория Хромова",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpg",
    username: "Полина Попова",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpg",
    username: "Алиса Миронова",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpg",
    username: "Варвара Комарова",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Лучший вид в Малайзии! Любовь!",
    photo: "assets/post/1.jpg",
    date: "5 минут назад",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpg",
    date: "15 минут назад",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Где лучше выбрать отель в горах? Конечно же на верхушке горы!",
    photo: "assets/post/3.jpg",
    date: "1 час назад",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpg",
    date: "4 часа назад",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "5 часов назад",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpg",
    date: "1 день назад",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Кто не побывал на Великой китайской стене, тот не может считаться китайцем",
    photo: "assets/post/7.jpg",
    date: "2 дня назад",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpg",
    date: "3 дня назад",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Вот как растет ананас.",
    photo: "assets/post/9.jpg",
    date: "5 дней назад",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];